## Visualice the .parquet files saved in datalake_gold

Import libraries and declare paths

In [33]:
import pandas as pd
from pathlib import Path

GOLD_BASE_PATH = "../datalake_gold"

# Ver todos los archivos disponibles
gold_files = sorted(Path(GOLD_BASE_PATH).glob("*.parquet"))
for f in gold_files:
    print(f.name)

governance_news_20260530_015150.parquet
governance_tweets_20260530_015149.parquet
storytelling_news_daily_volume_20260530_015204.parquet
storytelling_news_nlp_base_20260530_015208.parquet
storytelling_tweets_daily_volume_20260530_015202.parquet
storytelling_tweets_lang_dist_20260530_015205.parquet
storytelling_tweets_nlp_base_20260530_015206.parquet

---

In [34]:
from pathlib import Path
import pandas as pd

pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", 200)

GOLD_PATH = Path("../datalake_gold")

parquets = sorted(GOLD_PATH.glob("*.parquet"))

print(f"Total datasets: {len(parquets)}")

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", None)
pd.set_option("display.max_colwidth", None)
pd.set_option("display.width", None)

for dataset in parquets:
    print("\n")
    print("=" * 100)
    print(dataset.name)

    df = pd.read_parquet(dataset)

    print(f"Rows: {len(df)}")
    print(f"Columns: {len(df.columns)}")

    display(df)

Total datasets: 7


====================================================================================================
governance_news_20260530_015150.parquet
Rows: 1
Columns: 6

,total_news,unique_news,duplicate_rows,duplicate_rate_pct,news_without_comments,no_comments_rate_pct
0,8,8,0,0.0,0,0.0

====================================================================================================
governance_tweets_20260530_015149.parquet
Rows: 1
Columns: 8

,total_tweets,unique_tweets,duplicate_rows,duplicate_rate_pct,verified_user_tweets,avg_tweet_length,min_tweet_length,max_tweet_length
0,60,60,0,0.0,0,265.866667,70,1070

====================================================================================================
storytelling_news_daily_volume_20260530_015204.parquet
Rows: 1
Columns: 2

     date_day  count
0  2026-05-29      8

====================================================================================================
storytelling_news_nlp_base_20260530_015208.parquet
Rows: 119
Columns: 3

,newsLink,date_day,comment_text
0,https://www.gsmarena.com/xiaomi_unveils_smart_band_10_pro_buds_6_sound_play_speaker-news-73032.php,2026-05-29,"I like how at least some still make earbuds without silicone tips. I really don't like those. \n \nAlso, is Xiaomi Watch S5 any good? I'm currently on old Galaxy Watch 4 and I'm slowly looking for alternatives or options..."
1,https://www.gsmarena.com/xiaomi_unveils_smart_band_10_pro_buds_6_sound_play_speaker-news-73032.php,2026-05-29,"is it still qualified as a smart ""band""? it's too big and heavy for a ""band"", just call it a smart ""watch"" at this point. not just xiaomi, huawei also made the exact same mistake"
2,https://www.gsmarena.com/xiaomi_unveils_smart_band_10_pro_buds_6_sound_play_speaker-news-73032.php,2026-05-29,"Hamad1993, 28 May 2026So this one or huwaei band 11?Wait for The Quantified Scientist YouTube channel to do his usual stress test regarding the Smart Band 10 Pro. He already did the Huawei Band 11, and the results are pretty good."
3,https://www.gsmarena.com/xiaomi_unveils_smart_band_10_pro_buds_6_sound_play_speaker-news-73032.php,2026-05-29,"dexterouz, 28 May 2026For that, I'm waiting for ""The Quantified Scientist"" review to drop. And pretty... moreHopefully he also reviews the watch S5, really curious if they improved sleep tracking."
4,https://www.gsmarena.com/xiaomi_unveils_smart_band_10_pro_buds_6_sound_play_speaker-news-73032.php,2026-05-29,"Anonymous, 28 May 2026Earbuds without eartips aka open earbuds are no go if you really love load and bassy music.Some people don't support to have something so deep in their ears"
5,https://www.gsmarena.com/xiaomi_unveils_smart_band_10_pro_buds_6_sound_play_speaker-news-73032.php,2026-05-29,Earbuds without eartips aka open earbuds are no go if you really love load and bassy music.
6,https://www.gsmarena.com/xiaomi_unveils_smart_band_10_pro_buds_6_sound_play_speaker-news-73032.php,2026-05-29,"Hamad1993, 28 May 2026So this one or huwaei band 11?For that, I'm waiting for ""The Quantified Scientist"" review to drop. And pretty sure it will take some time. He has already reviewed Mi Band 10, Huawei Band 11 and 11 Pro."
7,https://www.gsmarena.com/xiaomi_unveils_smart_band_10_pro_buds_6_sound_play_speaker-news-73032.php,2026-05-29,How are they doing 2.1mbps when snapdragon sound max bitrate was 1.2mbps? Did I miss something?
8,https://www.gsmarena.com/xiaomi_unveils_smart_band_10_pro_buds_6_sound_play_speaker-news-73032.php,2026-05-29,"""Xiaomi unveils Smart Band 10 Pro, Buds 6, Sound Play speaker \nXiaomi also unveiled something new - the Sound Play, which admittedly is the way a neanderthal might ask his Gemini or Alexa to play some music."" \n \nLoving the description 🤣"
9,https://www.gsmarena.com/xiaomi_unveils_smart_band_10_pro_buds_6_sound_play_speaker-news-73032.php,2026-05-29,So this one or huwaei band 11?
10,https://www.gsmarena.com/samsung_is_now_shipping_samples_of_hbm4e_memory_which_is_faster_and_has_higher_capacity-news-73047.php,2026-05-29,Ai sux
11,https://www.gsmarena.com/samsung_is_now_shipping_samples_of_hbm4e_memory_which_is_faster_and_has_higher_capacity-news-73047.php,2026-05-29,Ai will ruin this planet
12,https://www.gsmarena.com/samsung_is_now_shipping_samples_of_hbm4e_memory_which_is_faster_and_has_higher_capacity-news-73047.php,2026-05-29,AI will hallucinate and give you the wrong answer much quicker.
13,https://www.gsmarena.com/samsung_is_now_shipping_samples_of_hbm4e_memory_which_is_faster_and_has_higher_capacity-news-73047.php,2026-05-29,you read it right - its for AI-thingy
14,https://www.gsmarena.com/samsung_is_now_shipping_samples_of_hbm4e_memory_which_is_faster_and_has_higher_capacity-news-73047.php,2026-05-29,Huhn???!
15,https://www.gsmarena.com/samsung_is_now_shipping_samples_of_hbm4e_memory_which_is_faster_and_has_higher_capacity-news-73047.php,2026-05-29,"If its not for consumer market, why bother writing it as it just make people more angry that they not gonna get it -_-"
16,https://www.gsmarena.com/samsung_galaxy_z_fold8_fold8_ultra_crease_free_display_tipped-news-73038.php,2026-05-29,Waiting for the day Samsung increases battery capacity on the phones
17,https://www.gsmarena.com/vertu_unveils_alphafold_its_first_bookstyle_foldable_and_boasts_about_its_hermes_ai_agent-news-73049.php,2026-05-29,Rebranded zte with leather slapped onto it. Doesnt worth at this price
18,https://www.gsmarena.com/vertu_unveils_alphafold_its_first_bookstyle_foldable_and_boasts_about_its_hermes_ai_agent-news-73049.php,2026-05-29,"Anonymous, 27 minutes agoOne year old chip for 6k. What a joke. you can build a whole computer that is miles better than whatever that is with that price"
19,https://www.gsmarena.com/vertu_unveils_alphafold_its_first_bookstyle_foldable_and_boasts_about_its_hermes_ai_agent-news-73049.php,2026-05-29,One year old chip for 6k. What a joke.
20,https://www.gsmarena.com/vertu_unveils_alphafold_its_first_bookstyle_foldable_and_boasts_about_its_hermes_ai_agent-news-73049.php,2026-05-29,"Skoda9635, 59 minutes agoHard to say what is worse, Honor Purse or this. Well Purse came from Honor, so probably it got... moreat least with the purse there's an actual gimmick attached to it, and i actually liked it compared to the Vertu BetaFold"
21,https://www.gsmarena.com/vertu_unveils_alphafold_its_first_bookstyle_foldable_and_boasts_about_its_hermes_ai_agent-news-73049.php,2026-05-29,"VYNI - LosEstupido, 1 hour agoi love when phones are treated like fashion statements more than actual utility devices with f... moreI agree with absolutely everything you said, the reason I like (the concept) though is because it's so bad that it's actually good LOL (I don't support vertu and think they're terrible btw)"
22,https://www.gsmarena.com/vertu_unveils_alphafold_its_first_bookstyle_foldable_and_boasts_about_its_hermes_ai_agent-news-73049.php,2026-05-29,"VYNI - LosEstupido, 1 hour agoi love when phones are treated like fashion statements more than actual utility devices with f... moreHard to say what is worse, Honor Purse or this. Well Purse came from Honor, so probably it got some software updates and customer service and maybe QA was better."
23,https://www.gsmarena.com/vertu_unveils_alphafold_its_first_bookstyle_foldable_and_boasts_about_its_hermes_ai_agent-news-73049.php,2026-05-29,"Stupid Chinese company that bought the OG Vertu brand. Faking ads with AI, faking luxury by using Nubia phones. Pure scam."
24,https://www.gsmarena.com/vertu_unveils_alphafold_its_first_bookstyle_foldable_and_boasts_about_its_hermes_ai_agent-news-73049.php,2026-05-29,"WitheredSoul, 1 hour agoBuns company, buns phone, absurd, absolutely atrocious price.\n\nLove it fr, keep it coming Ve... morei love when phones are treated like fashion statements more than actual utility devices with fun gimmicks on the side. this company has to be the worst out of all companies i've seen, genuinely why would someone need a Vertu? do they wanna use it as a utility product? literally any phone with a Snapdragon 8 Elite SoC and even iPhones are miles cheaper than it. do they want it as a fashion statement? iPhone Pros exist, you'd probably have a better experience with them than whatever outlandish UX this company makes. \n \nalso love the AI images they used for the ads, keep it going vertu: the super duper ultra premium brand, the alpha and the omega."
25,https://www.gsmarena.com/vertu_unveils_alphafold_its_first_bookstyle_foldable_and_boasts_about_its_hermes_ai_agent-news-73049.php,2026-05-29,"I hope the Enigma (Zack JRE) tests it after getting it from another Alpha (MKBHD). will it prove itself to be a true Alpha, or will it be an Omega pretending to be an Alpha..."
26,https://www.gsmarena.com/vertu_unveils_alphafold_its_first_bookstyle_foldable_and_boasts_about_its_hermes_ai_agent-news-73049.php,2026-05-29,Nubia Fold Vertu edition
27,https://www.gsmarena.com/vertu_unveils_alphafold_its_first_bookstyle_foldable_and_boasts_about_its_hermes_ai_agent-news-73049.php,2026-05-29,"Buns company, buns phone, absurd, absolutely atrocious price. \n \nLove it fr, keep it coming Vertu, I like seeing outlandish products"
28,https://www.gsmarena.com/hmd_grand_renders_and_specifications_leak-news-73024.php,2026-05-29,"-, 28 May 20261. How did you get banned in under a minute ???\n2. Showed up in certifications, IMEI database... moreOh, okay. I guess we will have to wait and see what they come up with. If it's anything like the Asha models, that will be nice. I hope it comes with a usable OS though, not S30+ or RTOS Touch or whatever it is called. \n \nAnd I didn't get banned or anything. I just don't have an account anymore. I post without signing up - rarely only now. People argue too much on here, so I keep my distance. :)"
29,https://www.gsmarena.com/hmd_grand_renders_and_specifications_leak-news-73024.php,2026-05-29,Missing stuff that would actually make it viable. This is e waste
30,https://www.gsmarena.com/hmd_grand_renders_and_specifications_leak-news-73024.php,2026-05-29,Dead on arrival.
31,https://www.gsmarena.com/hmd_grand_renders_and_specifications_leak-news-73024.php,2026-05-29,"AnonD-1231567, 28 May 2026Huh? Where’d you hear this news? If it’s true, I’ll get one for sure! 🥳1. How did you get banned in under a minute ??? \n2. Showed up in certifications, IMEI database and on a page on HMD's website for SAR value information. Idk what it's like but it will probably be HMD's flagship product for the year, headlining the AI feature set on feature phones which was first introduced on Chinese HMD 101 and 102 4G models last year"
32,https://www.gsmarena.com/hmd_grand_renders_and_specifications_leak-news-73024.php,2026-05-29,"The HMD Grade looks promising — if only the rounded corners on this phone matched the precision of the camera module, it would be more balanced.✨"
33,https://www.gsmarena.com/hmd_grand_renders_and_specifications_leak-news-73024.php,2026-05-29,"-, 28 May 2026By the way if anyone's wondering I don't think HMD is Actually working on any new sm... moreHuh? Where’d you hear this news? If it’s true, I’ll get one for sure! 🥳"
34,https://www.gsmarena.com/hmd_grand_renders_and_specifications_leak-news-73024.php,2026-05-29,"Pumpino, 28 May 2026E-waste. At least HMD is no longer dragging Nokia's name through the mud. I wonder if we&... moreI'm neither excited nor disappointed, knowing that none of the devices shared by that user gets actually released."
35,https://www.gsmarena.com/hmd_grand_renders_and_specifications_leak-news-73024.php,2026-05-29,"Anonymous, 28 May 20266,000mAh battery vs samsung's 5,000mAh = ✔️\n6GB RAM (base) vs samsung's 4GB RAM (ba... moredon't. HMD deliver quarterly update across all devices these days including my own Skyline. The real concern is their frequency to update the phone in case there's a critical bug, and I lose LE Audio when HMD updated this phone to android 15 and never enabled it back. While I don't like Samsung, that A17 is better in the long run or get CMF phones if you prefer near stock and few bloat"
36,https://www.gsmarena.com/hmd_grand_renders_and_specifications_leak-news-73024.php,2026-05-29,"4g, wifi 5, bezels thick as phones from 10 years ago, 33w charging, 90hz lcd, poor soc. \n \nThis phone is a budget phone from 5 years ago."
37,https://www.gsmarena.com/hmd_grand_renders_and_specifications_leak-news-73024.php,2026-05-29,It's vivo Y16 from 2022
38,https://www.gsmarena.com/hmd_grand_renders_and_specifications_leak-news-73024.php,2026-05-29,"DarlingYext, 28 May 2026Looks like a generic Oppo A6 model, and is just as much of an e-waste. HMD should focus on the... moreHmd luna as same as Oppo A6"
39,https://www.gsmarena.com/hmd_grand_renders_and_specifications_leak-news-73024.php,2026-05-29,50MP selfies oh great like the Pulse Pro and the MIA Pulse 2 Pro née the actually launched M-Kopa X30.
40,https://www.gsmarena.com/hmd_grand_renders_and_specifications_leak-news-73024.php,2026-05-29,The processor is snapdragon 6s gen2 4G
41,https://www.gsmarena.com/hmd_grand_renders_and_specifications_leak-news-73024.php,2026-05-29,By the way if anyone's wondering I don't think HMD is Actually working on any new smartphones BUT! They have the TA-1779 aka Asha 305 coming up. Yes I'm serious
42,https://www.gsmarena.com/hmd_grand_renders_and_specifications_leak-news-73024.php,2026-05-29,"Like a Redmi 15c without the nipple notch same size and style. \n \nWho wants a 6.9"" brick \n \nWhy can they not go about looking at a successor to the skyline \n \nOh and the 2 OS updates I would take with a rather large pinch of salt as they fall back on their promises all the time. \n \nI believe they still have that gargling audio bug in video camera on the Pulse models they never bothered to fix."
43,https://www.gsmarena.com/hmd_grand_renders_and_specifications_leak-news-73024.php,2026-05-29,At least it's not HD+ display. Hope those crap finally get btfo'd out of existence.
44,https://www.gsmarena.com/hmd_grand_renders_and_specifications_leak-news-73024.php,2026-05-29,"6,000mAh battery vs samsung's 5,000mAh = ✔️ \n6GB RAM (base) vs samsung's 4GB RAM (base) = ✔️ \n3 years support (OS and security) vs samsung's 6 years support (OS and security) = ❌ \nand a 3.5mm headphone jack = ✔️ \nSD card slot = ❓ \n \nDefinitely better than A17, and I am 75% considering this phone. \nIf the price is around $100 ~ $110 USD (€85 ~ €95 EUR), then I'm sold! \n \nKeep in mind that samsung is raising the prices of their phone due to the worker strike..... I mean, the artifical RAM shortage caused by the RAM triopoly cartel (samsung, s k hynix, and micron). \nBut definitely not greed, oh no. Not greed at all. \nhttps://www.gsmarena.com/samsung_is_forced_to_raise_prices_due_to_everrising_ram_prices-news-72997.php"
45,https://www.gsmarena.com/hmd_grand_renders_and_specifications_leak-news-73024.php,2026-05-29,"Looks like a generic Oppo A6 model, and is just as much of an e-waste. HMD should focus on the Skyline series, and stop releasing any other nonsensical phone, like this one."
46,https://www.gsmarena.com/hmd_grand_renders_and_specifications_leak-news-73024.php,2026-05-29,E-waste. At least HMD is no longer dragging Nokia's name through the mud. I wonder if we'll see the Skyline 2 at some stage.
47,https://www.gsmarena.com/hmd_grand_renders_and_specifications_leak-news-73024.php,2026-05-29,"Snapdragon 6s Gen 2 is rebranded or overclocked version of Snapdragon 685, no thanks HMD"
48,https://www.gsmarena.com/oura_ring_5_announced_with_slim_design_updated_sensors_and_blood_pressure_monitoring_-news-73036.php,2026-05-29,"pl2rts, 7 hours agoYou get a really good middle class phone for the money that they ask while ripping off Europea... moreI've personally found Oura to be the most accurate tracking when sleeping for me, better than other devices I've tried. I also dislike wearing a watch/band overnight. I'm in the US though, so prices are lower than the EU. I can easily afford it and for me, health monitoring is worth it as I love data."
49,https://www.gsmarena.com/oura_ring_5_announced_with_slim_design_updated_sensors_and_blood_pressure_monitoring_-news-73036.php,2026-05-29,"pl2rts, 7 hours agoYou get a really good middle class phone for the money that they ask while ripping off Europea... moreTech companies outside Europe are overpricing their products in Europe. \n \nChinese flagship phone could cost almost half the price in China but in Europe even if we add 25 percent vat phone could be priced almost the double here. \n \nSome United States tech companies does this too."
50,https://www.gsmarena.com/oura_ring_5_announced_with_slim_design_updated_sensors_and_blood_pressure_monitoring_-news-73036.php,2026-05-29,You get a really good middle class phone for the money that they ask while ripping off Europeans with a lot higher price. 399 dollars is around 342 euro and they ask 429 for it that is like 499 dollars. \n \nWhile the color is different they ask 100 dollars or 100 euro for the color only is even more insane. \n \nAhh well in the end of the day the people who buy this deserve to be ripped off if they are willing to spend so much on so small thing with just few censors built in it
51,https://www.arenaev.com/xiaomi_ceo_personally_delivers_first_yu7_gt_vehicles_to_buyers_in_china-news-5928.php,2026-05-29,"Anonymous, 29 Apr 2013how often do we wear glove? LOL\n\nEvery weekday at my job... :)"
52,https://www.arenaev.com/xiaomi_ceo_personally_delivers_first_yu7_gt_vehicles_to_buyers_in_china-news-5928.php,2026-05-29,"AnonD-140756, 29 Apr 2013why ddnt anyone mention the sony xperia z display in this article ? ^o)Because it is really crap!"
53,https://www.arenaev.com/xiaomi_ceo_personally_delivers_first_yu7_gt_vehicles_to_buyers_in_china-news-5928.php,2026-05-29,"AnonD-87222, 27 Apr 2013I really reccomend the LCD crowd to try using AMOLED. You'll never want to look at LCDs ever a... moreUntil you use it outside and with the sun shining directly on it. \nOLED is known to be very weak in that aspect."
54,https://www.arenaev.com/xiaomi_ceo_personally_delivers_first_yu7_gt_vehicles_to_buyers_in_china-news-5928.php,2026-05-29,why ddnt anyone mention the sony xperia z display in this article ? ^o)
55,https://www.arenaev.com/xiaomi_ceo_personally_delivers_first_yu7_gt_vehicles_to_buyers_in_china-news-5928.php,2026-05-29,"AnonD-123779, 27 Apr 2013Ppl writing stories here. Samsung accepted s4 s not best. Then y cry over herebut fanboys think it is the best"
56,https://www.arenaev.com/xiaomi_ceo_personally_delivers_first_yu7_gt_vehicles_to_buyers_in_china-news-5928.php,2026-05-29,"MOD, 28 Apr 2013btw..just to reply on 1 point... s4 works with gloves on!how often do we wear glove? LOL"
57,https://www.arenaev.com/xiaomi_ceo_personally_delivers_first_yu7_gt_vehicles_to_buyers_in_china-news-5928.php,2026-05-29,"Anonymous, 27 Apr 2013Lumia 920' screen has Clearblack (best display for viewing in bright sunlight), fastest displa... morebtw..just to reply on 1 point... s4 works with gloves on!"
58,https://www.arenaev.com/xiaomi_ceo_personally_delivers_first_yu7_gt_vehicles_to_buyers_in_china-news-5928.php,2026-05-29,"Anonymous, 27 Apr 2013Lumia 920' screen has Clearblack (best display for viewing in bright sunlight), fastest displa... moreit just got beaten :P"
59,https://www.arenaev.com/xiaomi_ceo_personally_delivers_first_yu7_gt_vehicles_to_buyers_in_china-news-5928.php,2026-05-29,Nokia/WP again? Lumia Lumia Lumia... almost every thread on GSMArena there is someone finding a way to inject Nokia/WP into the comments/reviews. I'm beginning to suspect it's a paid effort by Nokia or Microsoft.
60,https://www.arenaev.com/xiaomi_ceo_personally_delivers_first_yu7_gt_vehicles_to_buyers_in_china-news-5928.php,2026-05-29,"Anonymous, 27 Apr 2013They forgot to compare Galaxy S4' screen to the Lumia 920's. Lumia 920' screen pretty much bea... moreLumia 920' screen has Clearblack (best display for viewing in bright sunlight), fastest display on mobile with PureMotion (LCD overdrive), and Supersensitive touch (works with gloves). That's hard to beat."
61,https://www.arenaev.com/xiaomi_ceo_personally_delivers_first_yu7_gt_vehicles_to_buyers_in_china-news-5928.php,2026-05-29,They forgot to compare Galaxy S4' screen to the Lumia 920's. Lumia 920' screen pretty much beat iPhone 5's in every category you can think of. \n \nhttp://blog.gsmarena.com/apple-iphone-5-display-compared-to-nokia-lumia-920-has-its-most-advanced-title-taken-away/

====================================================================================================
storytelling_tweets_daily_volume_20260530_015202.parquet
Rows: 1
Columns: 2

     date_day  count
0  2026-05-28     60

====================================================================================================
storytelling_tweets_lang_dist_20260530_015205.parquet
Rows: 3
Columns: 2

  lang  count
0   en     57
1   in      2
2   tl      1

====================================================================================================
storytelling_tweets_nlp_base_20260530_015206.parquet
Rows: 60
Columns: 10

,id,date_day,author_userName,text_cleaned,total_engagement,lang,likeCount,replyCount,retweetCount,quoteCount
0,2060004476669374743,2026-05-28,SouthernFreeez,"1/ Really disappointed with Bose ending cloud support for the SoundTouch 20. I bought this as a premium connected speaker system, not just a basic Bluetooth speaker. Now Bose has effectively stripped away key functionality from a product customers paid hundreds for.",1,en,0,1,0,0
1,2059950505447584179,2026-05-28,oluwafemi10591,"I got into a screaming match on the bus this morning, and honestly, I don't care if the whole vehicle thought I was crazy. ​This guy gets on, sits right across from me, and immediately blasts a video on his phone at full volume. No headphones. Just pure, distorted audio filling the entire space. I tolerated it for five minutes, hoping it was just a quick clip. It wasn’t. ​I politely asked him, Big man, do you mind putting on headphones? It's a bit loud. He looked me dead in the eye and said, If you don’t want to hear it, buy a car. It’s a public space, I can do what I want. ​The absolute entitlement blew my mind. I didn’t even argue. I pulled out my phone, opened an annoying alarm sound, maxed out my volume, and held it right next to his ear. He lost his mind, calling me psyco and aggressive. A few people on the bus told me I should have just ignored him, while others cheered. ​When did public space become an excuse to have zero home training? Am I wrong for fighting fire with fire, or are people way too comfortable being completely rude in public?",1,en,1,0,0,0
2,2059950392176234910,2026-05-28,oluwafemi10591,"I got into a screaming match on the bus this morning, and honestly, I don't care if the whole vehicle thought I was crazy. ​This guy gets on, sits right across from me, and immediately blasts a video on his phone at full volume. No headphones. Just pure, distorted audio filling the entire space. I tolerated it for five minutes, hoping it was just a quick clip. It wasn’t. ​I politely asked him, Big man, do you mind putting on headphones? It's a bit loud. He looked me dead in the eye and said, If you don’t want to hear it, buy a car. It’s a public space, I can do what I want. ​The absolute entitlement blew my mind. I didn’t even argue. I pulled out my phone, opened an annoying alarm sound, maxed out my volume, and held it right next to his ear. He lost his mind, calling me psyco and aggressive. A few people on the bus told me I should have just ignored him, while others cheered. ​When did public space become an excuse to have zero home training? Am I wrong for fighting fire with fire, or are people way too comfortable being completely rude in public?",1,en,1,0,0,0
3,2059937735977398654,2026-05-28,GearReview,"Ever forget you’re wearing earbuds until the battery dies? We tested the Sony LinkBuds Fit through workouts, errands, and long days. Worth it?",0,en,0,0,0,0
4,2059914754030776460,2026-05-28,CDLHater,"Dashy talks about Mercules' camera falling on main stage 😂🗣️ Dashy : ""I got new sound proof earbuds, I can't hear nothing but the camera drop scared THE F*CK out of me, this guys an alien &amp; he almost 1v4's"" Mercules : ""I didn't even notice it, I noticed nothing at all"" 🤣",395,en,391,0,4,0
5,2059899870865932490,2026-05-28,6060_0606,this was my favorite solo i used to play it every time i bought new headphones to test the sound 😭,1,en,0,1,0,0
6,2059872425068704029,2026-05-28,merrygomaru,when I left japan the last time I bought bluetooth headphones and named them “marumaxxer” n then I wrote about seeing him to practice japanese on the plane.. “I’ve never had an oshi so fast” right.. 🤣,15,en,15,0,0,0
7,2059782299370070471,2026-05-28,tytiethai_,"Completed my mini home theater set up thingy for my bday, Sony a90k 48inch TV, Panasonic ub820 4k player, Ps5 pro, and Samsung q990f sound bar with sub and rear speakers. EXTREMELY happy with it. Now I can frame all my posters and really start decorating ☺️",0,en,0,0,0,0
8,2059696184248401937,2026-05-28,saffronandsky,When my Garmin watch falls off at night and has no data so it resets my body battery to 50. Ha! As if. It hasn't recharged to above 30 in the 3 and 1/2 years since I got it...,2,en,2,0,0,0
9,2059641565706871191,2026-05-28,My_Capering_Id,"Big buyer's remorse on the the choice of color (they had a nice variety, including fire engine red) I got for my new JBL portable bluetooth speaker to hang from my handlebars when I go biking. It looks like a Fleshlight® 🫤",0,en,0,0,0,0
10,2059597381109440747,2026-05-28,sixsevenahhblud,I just watched a stereo test video on YouTube and realized my earbuds I got for free had the left audio on the right side and vice versa,0,en,0,0,0,0
11,2059467952928559187,2026-05-28,RRobovski,I got fed up with streaming and got a mp3 player with Bluetooth so I can use it in the car or with my wireless headphones but it also has a 3.5 jack for flexibility.,1,en,0,1,0,0
12,2059422706005614858,2026-05-28,clueless_trade,"I got a new 🐇🕳️ for ….emf! is our AirPods, Bluetooth, WiFi etc toxic",0,en,0,0,0,0
13,2059421694306206106,2026-05-28,Zeke_The_Human,"I've been using earbuds for streaming the past few months, I liked them but the downside was when I kept speaking they usually get loose. Just got Audio Technica ATH-EQ300M Very cheap so didn't expect much but with watching a few videos they sound great.",21,en,16,3,2,0
14,2059338698131419241,2026-05-28,WizzyLizzy06,"i was tryna get my headphone jack into my monitor, i had my headphones on and the static sound as i got closer sounded like i was edging it funny",2,en,2,0,0,0
15,2059334459598499931,2026-05-28,commsonawire,"Quick test of my new Tufteln audio breakout board / microphone for the TX500. Tiny compared to the stock microphone and lets me use headphones. I got the cover too, which is more compact than the one I printed.",18,en,16,1,1,0
16,2059265460542095608,2026-05-28,DurvidImel,"I've been using the FitBit Air for about a week and I'm working on some longer-form thoughts for later on, but my high-level thoughts right now are: ✅ Light and small form factor is ideal for long-term wear and sleep ✅ Battery life is wonderful. I'm 1-week in and still at 32%",1363,en,1310,38,15,0
17,2059250440798146655,2026-05-28,AllAcesCards,"Does anyone have a smart watch with great battery life? My FitBit just died. I bought a Garmin VivoActive because the reviews said it would last 10-11 days on 1 charge - in real life it lasted about 2 days, so I’m returning it. Any recommendations?",3,en,1,2,0,0
18,2059217412202057937,2026-05-28,maihimebow,i bought regular sony shmegular earbuds (not iems) just so i can have something when my airpods are charging Oh its so good not to worry about that damn battery,0,en,0,0,0,0
19,2059206596811776120,2026-05-28,hegaumai,Heartbreaking: audio from the earphones i got for less than one dollar online sounds so much worse than my broken $40 sam5ung earbuds,0,en,0,0,0,0
20,2059901653986181162,2026-05-28,craniosurgeon,"BS. My 22yr old MacBook starts and runs like on the day I bought it. Sure, the keyboard is worn and the screen hinge is loose but the thing still works. That doesn’t happen with a windows machine. The two reasons people buy Apple are UI and UE.",0,en,0,0,0,0
21,2059864746392781018,2026-05-28,wisedawn13,"Crazy to think that I've had my macbook pro for TEN (10) YEARS and it works just as good as the day I got it. It is not slow, it does not lag, I can just close the lid without turning it off for however long and when I turn it on again everything will still be there... Amazing",1,en,0,1,0,0
22,2059819697735094584,2026-05-28,DaveTaylor,"The PELADN WO4 AMD Ryzen 5 Mini PC is an amazing little device: It'll fit in the palm of your hand, but offers impressive performance and Windows 11 Pro. I got my hands on one and ran it through its paces... #windowspc #minipc #windows",0,en,0,0,0,0
23,2059808927743893993,2026-05-28,SnazzyLabs,"You may think that I bought my MacBook Pro because of its best in class silicon, it’s excellent battery, it’s wonderful mini-LED screen, it’s incredible glass haptic trackpad, but NO!!! I bought my Apple because of my perception of community. THAT is worth $1,800 to me.",2095,en,2013,41,39,2
24,2059760658950861291,2026-05-28,8kPegasus,Why don’t we talk about how many times Microsoft accounts try to get hacked ? I bought a 5080 msi gaming laptop it’s dust covered even with years worth of internet protection I’m getting notifications of attacks I haven’t even turned that shit on since February,0,en,0,0,0,0
25,2059750854589026479,2026-05-28,Noah_C_Moore,I think I got 6p into this at like half screen and got wall broke and died bro shit was atleast 30% of my hp 😂😂😂,0,en,0,0,0,0
26,2059714859189600748,2026-05-28,minallkamel,i bought a dell keyboard and it's the smoothest thing i've ever tried it make me wanna write c++ just to type more,2,en,1,1,0,0
27,2059661083883753815,2026-05-28,Samurai__Stock,"Pretty happy with my YTD performance: +17% while the S&P 500 is up just +9%. My long-term goal for the account is 20% CAGR, and I’m confident these names will help get me there: $AMD $META $AMZN $MSFT $AXP $CRM $SOFI $CELH $ELF $AXON $ASML $HIVE $NOW $NFLX What are your top conviction names right now?",12,en,8,2,1,1
28,2059559483462816010,2026-05-28,Autoweltmedia,"Audi B9 S5 launched in 2017 on the MLB Evo platform with a 3.0L turbocharged V6, 354 HP and 500 Nm of torque. Lighter than the B8 it replaced, wider track, longer wheelbase, and a larger cabin. As a daily driver it is one of the most liveable performance coupes available - refined enough for long motorway journeys, fast at a B-road, and the V6 and torque converter automatic combination is proving to be one of the most reliable setups in any German car. The engine is shared across the Porsche Cayenne and Panamera, which tells you how solid it is.",31,en,26,1,4,0
29,2059260000581681547,2026-05-28,GHSTCraft420,wanted to say I bought my first gaming pc from u guys its still getting assembled and all that but I trust u guys more then any other pc brand,2,en,1,1,0,0
30,2058870136543617235,2026-05-28,ViberPsychosis,My #Hermes agents run on a scrap macbook ait with now screen i got off ebay for less than 100 of your british pounds. I originaly had it running on a £40 Dell optiplex off ebay but i wanted apple integration. You DON'T need a VPS or expensive hardware.,0,en,0,0,0,0
31,2058746234400076009,2026-05-28,Ark13Vongdara,?iQ1 Secret ?iQ1 How my intel know they Turn off the Camera i got Pointed at the door an attic Before they Go talk to them in the attic the Headphone i hang at the attic has a wifi gaming headset it has a Hot Mic you can Hack an hear record everything they plotting with the attic,0,en,0,0,0,0
32,2058743641645150533,2026-05-28,timhnln,"I have seen the future with far less impressive hardware on hand. This morning I got OpenCode hooked up to a quantized Qwen3.6-35B-A3B, which was running on a 24GB RTX 3090 in my old gaming PC, over the network.",1,en,1,0,0,0
33,2058722411030196719,2026-05-28,CassieKatarn,A couple years ago I got really high and watched a bunch of early 70s sci-fi and then topped it off woth the og trilogy and it majorly shifted how I viewed them This was back when I was still on the farm with a giant inflatable movie screen amd projector,2,en,1,1,0,0
34,2058603864220139575,2026-05-28,RaineOW_,10 years ago I bought Overwatch (instead of Battleborn) on my HP laptop I had for university. I got 20 fps and only played Mercy on terrible university dorm wifi. 19 year old Raine would have NO IDEA how much of an impact the game would have on her 🥹 Happy anniversary Overwatch!,22,en,20,2,0,0
35,2058554894424891801,2026-05-28,only1rawr,"Would love some performance optimization for I got 64gb ddr5 ram & an intel i9 13950hx raptor lake processor. I should be able to load every plugin I want & mix while recording... That's my work flow... Except, if I put multiple plugins, it starts moving weird as hell, crackling etc... UAD APOLLO TWIN X GEN 1 INTERFACE... Feel like I can't even utilize this beast how I want too...",0,en,0,0,0,0
36,2058467915050148101,2026-05-28,MishraSheesh,"I am extremely unhappy with the product and service of your company. I bought a laptop, Lenovo Flex 5i from your store 2 years back and since then it has been a struggle. The front camera always shows green screen, it's from day 1. Disappointed &amp; wary",3,en,0,3,0,0
37,2058414679899443220,2026-05-28,MiaJuanda7,"Kapan lagi dapet HP yang all-in-one kayak Infinix HOT 70? Desain velvet smooth-nya dapet, performa buat gaming aman, baterai jumbo pula. Bener-bener definisi HP mid-range yang worth it banget buat dibeli tahun ini.",0,in,0,0,0,0
38,2058413807840714814,2026-05-28,Gilang9043,"nyari hp mid-range yang paket lengkap buat gaming tipis-tipis ama awet seharian ya Infinix HOT 70 jawabannya, worth it bgt buat anak muda gen z cocok",0,in,0,0,0,0
39,2058391958280716643,2026-05-28,Chief900Bill,"I got a ton of computers, so i be tryna be nice and let my son game on HQ lenovo gaming laptop but dude just keep disrespecting it soon as he done... like bro who do you see just leave they PC on all day😂😅",0,en,0,0,0,0
40,2059892944702984655,2026-05-28,nagh_siva,"I've been using these Galaxy Buds FE since February 2024, &amp; they seriously one of the best TWS for my Samsung smartphone. *Punchy, enriched bass &amp; surround sound (better than Galaxy Buds Pro) *Powerful ANC *Good battery life *The best ergonomic wingtip design *Timely updatess",1,en,1,0,0,0
41,2059875042381721992,2026-05-28,VikashK35321493,"I am using the Xiaomi 14 device, which I bought in November 2025. This phone was working fine before, but for the past few months, it has started giving a lot of trouble. Its camera has started lagging, and the phone hangs and switches off on its own, then switches",1,en,0,1,0,0
42,2059869422777450814,2026-05-28,HK_Urban,New iPhone drop has me broke but hyped That camera tho… worth it? TechLife Apple 👍,0,en,0,0,0,0
43,2059837030629359975,2026-05-28,phonescloud99,"Testing Android from an iPhone. The game runs on a real cloud Android device. The iPhone is just the control screen. Not for heavy daily gaming, but useful for short checks: latency, loading, account flow, and whether a spare device is worth it.",1,en,1,0,0,0
44,2059767572640280601,2026-05-28,Bigwavee00,"With my experience as a phone vendor, this is what I’ve to say…. The Pixel 10 brings a bold, modern and unique design that stands out instantly with its signature camera bar and premium Android feel. The iPhone Air on the other hand delivers a clean, ultra-sleek and minimalist luxury design built for lovers of simplicity and elegance. One is bold and expressive. The other is calm and premium. No matter your taste, both devices were designed to turn heads. 🔥 The question is which will you personally prefer.",74,en,40,10,24,0
45,2059730259835044211,2026-05-28,D4rkwinger,"Never buy a Samsung Galaxy A03 no matter how desperate you are to get a lost phone replaced ASAP, Motorola is the best Android brand for cheap phones, I got a stick to them.",8,en,7,1,0,0
46,2059716370187563072,2026-05-28,Ajayi_tweets,"IPhones are overrated. I had been trying to subscribe to Twitter Premium+ for over a year, all to no avail because of the iPhone. I got a new Android yesterday, and this morning Google Play accepted my payment request and the subscription went through.",0,en,0,0,0,0
47,2059688011512913978,2026-05-28,pixeluibygoogle,"How many Pixel phones have you used so far, and which Pixel are you using right now? Are you happy with your phone? 🙂‍↕️",247,en,108,132,6,1
48,2059627109015064990,2026-05-28,joshubaeks,pano nga magembed vid sa iphone??? i got no problem sa android ko hays,1,tl,0,1,0,0
49,2059590519563718940,2026-05-28,GamerBraves,"You forgot your camera but the Xiaomi 17T Pro said ""don't worry, I got you."" #Xiaomi #Xiaomi17TPro",0,en,0,0,0,0
50,2059565167050989784,2026-05-28,CallmeRehoboth,"I sell my iPhone last year, con Dey use android I nearly kpai😭😂, Thank God I got a new one now tho😂.",2,en,2,0,0,0
51,2059548720102797410,2026-05-28,queenbeth____,"I remember when I bought my digital camera and people kept saying its trend, you don’t need it, the pictures are too yellow or orange deni, iPhone is better, even one of my friend said the same thing lmao, now look at everybody wanting a digital camera😭 That’s why you will never see me discouraging people from trying things they like. As long as you can afford it and it makes you happy, me I will support you o",1704,en,1613,36,53,2
52,2059472362417099099,2026-05-28,imDev02,"1.5 years ago, I bought these OnePlus Bluetooth earphones online for around ₹2,500. But I never thought they would turn out like this. In the beginning, they worked really well. The battery backup was good, and the sound quality was also excellent. But as time passed, problems slowly started appearing. Now the battery backup has reduced to barely half an hour. Sometimes the earphones suddenly switch off while using them. And the sound quality is no longer the same — the audio has become very poor. Honestly, companies are looting customers so badly these days. At the time of launch, they promise one thing, but when the product actually reaches users, it turns out to be completely different. I would never recommend these Bluetooth earphones to anyone. And before buying any product, always check reviews from genuine verified users first.",99,en,53,21,14,11
53,2059419294560383391,2026-05-28,moonsunmates,yes i bought a new iphone just to have a better camera for the concert… only god can judge me,0,en,0,0,0,0
54,2059393522185163114,2026-05-28,DylSki02,4 years ago today I got the 13 pro max brand new. In good condition after all these years. Still running iOS 15.4 I do miss using this phone as a daily. #iphone #apple #ios,1,en,1,0,0,0
55,2059345048131494353,2026-05-28,HOODIE_ROSS222,Did yall know on iPhone your icons move as u move your phone side to side I know this cuz I got it screen cast to tv also your phone has a feature that lets your camera follow your eyes your phone is made for the neurolink thing without consent u can ask grok or whatever em I right,1,en,0,1,0,0
56,2059330248416661901,2026-05-28,TechSceneZA,"The vivo V70 FE 5G is here… and at R16,999, it’s trying to deliver a premium experience From the sleek design to the smooth AMOLED display and reliable performance, this might be one of the most balanced phones in its category right now. But is it worth it for YOU? #vivoV70FE",0,en,0,0,0,0
57,2059329134283657277,2026-05-28,U_cutz,"Contrary to popular belief, the Tesla battery does not degrade like your iPhone battery 🔋. It is much more durable, lasting up to 15-20 years. That's why I bought a Cybertruck and will never sell it! Time will tell!",4,en,3,1,0,0
58,2059294605825462357,2026-05-28,AstiaSeyen6838,"Samsung lowkey the most worth it good camera, smooth multitasking, banyak fitur, and it actually lasts long.",0,en,0,0,0,0
59,2059255061424087332,2026-05-28,Drixstarnothere,"What are y’all battery health in your IPhones? Mine is this, since I got it 2nd hand with 81% battery health already.",2,en,1,1,0,0